export interface Product {
  id: number
  title: string
  supplier: string
  location: string
  price: string
  rating: number
  reviews: number
  image: string
  images: string[]
  category: string
  quantity: string
  minOrder: string
  description: string
  specifications: Record<string, string>
  supplierInfo: {
    name: string
    established: string
    certifications: string[]
    rating: number
    totalReviews: number
  }
}

export const products: Product[] = [
  {
    id: 1,
    title: "Aluminum Scrap - 6061 Grade",
    supplier: "Precision Metals Co.",
    location: "Phoenix, AZ",
    price: "₹1,200/ton",
    rating: 4.7,
    reviews: 23,
    image: "/aluminum-scrap-metal-industrial.jpg",
    images: [
      "/aluminum-scrap-metal-industrial.jpg",
      "/aluminum-sheets-stacked.jpg",
      "/aluminum-ingots-industrial.jpg",
      "/aluminum-processing-facility.jpg",
    ],
    category: "metals",
    quantity: "15 tons",
    minOrder: "1 ton",
    description:
      "High-grade aluminum scrap from aerospace manufacturing. Perfect for recycling into new aluminum products.",
    specifications: {
      Grade: "6061-T6",
      Purity: "99.5%",
      "Moisture Content": "<0.1%",
      Contamination: "Minimal",
      Processing: "Clean, sorted",
    },
    supplierInfo: {
      name: "Precision Metals Co.",
      established: "1995",
      certifications: ["ISO 9001", "ISO 14001"],
      rating: 4.8,
      totalReviews: 156,
    },
  },
  {
    id: 2,
    title: "Polyethylene Pellets",
    supplier: "PlastiCorp Industries",
    location: "Atlanta, GA",
    price: "₹850/ton",
    rating: 4.5,
    reviews: 18,
    image: "/plastic-pellets-polyethylene.jpg",
    images: [
      "/plastic-pellets-polyethylene.jpg",
      "/plastic-pellets-white-industrial.jpg",
      "/plastic-manufacturing-facility.png",
      "/plastic-recycling-process.jpg",
    ],
    category: "chemicals",
    quantity: "30 tons",
    minOrder: "2 tons",
    description: "Clean PE pellets from packaging production. Suitable for manufacturing new plastic products.",
    specifications: {
      Type: "HDPE",
      Density: "0.95 g/cm³",
      "Melt Index": "0.3 g/10min",
      Color: "Natural/Clear",
      Contamination: "<0.05%",
    },
    supplierInfo: {
      name: "PlastiCorp Industries",
      established: "2001",
      certifications: ["FDA Approved", "ISO 9001"],
      rating: 4.6,
      totalReviews: 89,
    },
  },
  {
    id: 3,
    title: "Cotton Textile Waste",
    supplier: "Textile Recyclers Ltd.",
    location: "Mumbai, India",
    price: "₹450/ton",
    rating: 4.3,
    reviews: 31,
    image: "/cotton-textile-waste-fabric.jpg",
    images: [
      "/cotton-textile-waste-fabric.jpg",
      "/cotton-fabric-scraps-colorful.jpg",
      "/textile-manufacturing-waste.jpg",
      "/cotton-bales-industrial.jpg",
    ],
    category: "textiles",
    quantity: "25 tons",
    minOrder: "500 kg",
    description:
      "Clean cotton textile waste from garment manufacturing. Ideal for recycling into new fabrics or industrial applications.",
    specifications: {
      Material: "100% Cotton",
      Color: "Mixed colors",
      Contamination: "<2%",
      Moisture: "<5%",
      Processing: "Sorted, baled",
    },
    supplierInfo: {
      name: "Textile Recyclers Ltd.",
      established: "2008",
      certifications: ["GOTS", "ISO 9001"],
      rating: 4.4,
      totalReviews: 67,
    },
  },
  {
    id: 4,
    title: "Steel Shavings - Industrial Grade",
    supplier: "MetalWorks Industries",
    location: "Detroit, MI",
    price: "₹950/ton",
    rating: 4.6,
    reviews: 42,
    image: "/steel-shavings-industrial-metal.jpg",
    images: [
      "/steel-shavings-industrial-metal.jpg",
      "/steel-metal-shavings-pile.jpg",
      "/steel-machining-process.jpg",
      "/steel-recycling-facility.jpg",
    ],
    category: "metals",
    quantity: "40 tons",
    minOrder: "2 tons",
    description:
      "High-quality steel shavings from precision machining operations. Perfect for steel recycling and remelting processes.",
    specifications: {
      Grade: "Carbon Steel",
      Carbon: "0.3-0.6%",
      Contamination: "<0.5%",
      Size: "Fine shavings",
      Processing: "Magnetically separated",
    },
    supplierInfo: {
      name: "MetalWorks Industries",
      established: "1987",
      certifications: ["ISO 9001", "ISO 14001", "OHSAS 18001"],
      rating: 4.7,
      totalReviews: 203,
    },
  },
  {
    id: 5,
    title: "Chemical Solvents - Mixed",
    supplier: "ChemRecycle Solutions",
    location: "Houston, TX",
    price: "₹2,100/ton",
    rating: 4.4,
    reviews: 15,
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    category: "chemicals",
    quantity: "12 tons",
    minOrder: "500 kg",
    description:
      "Mixed industrial solvents from pharmaceutical manufacturing. Suitable for solvent recovery and reprocessing.",
    specifications: {
      Type: "Mixed organic solvents",
      Purity: "85-95%",
      "Water Content": "<2%",
      "Heavy Metals": "<10 ppm",
      Packaging: "Steel drums",
    },
    supplierInfo: {
      name: "ChemRecycle Solutions",
      established: "2012",
      certifications: ["EPA Licensed", "ISO 9001", "RCRA Certified"],
      rating: 4.5,
      totalReviews: 34,
    },
  },
  {
    id: 6,
    title: "Copper Wire Scrap",
    supplier: "ElectroScrap Co.",
    location: "Los Angeles, CA",
    price: "₹6,800/ton",
    rating: 4.8,
    reviews: 56,
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    category: "metals",
    quantity: "8 tons",
    minOrder: "100 kg",
    description:
      "Clean copper wire scrap from electrical installations. High purity copper suitable for remelting and wire production.",
    specifications: {
      Grade: "Bright & Shiny Copper",
      Purity: "99.9%",
      Insulation: "Stripped clean",
      Contamination: "None",
      Processing: "Hand sorted",
    },
    supplierInfo: {
      name: "ElectroScrap Co.",
      established: "2005",
      certifications: ["ISO 9001", "R2 Certified"],
      rating: 4.9,
      totalReviews: 128,
    },
  },
  {
    id: 7,
    title: "Denim Fabric Scraps",
    supplier: "Fashion Forward Ltd",
    location: "Los Angeles, CA",
    price: "₹200/ton",
    rating: 4.8,
    reviews: 34,
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    category: "textiles",
    quantity: "8 tons",
    minOrder: "200 kg",
    description:
      "Premium denim scraps from garment manufacturing. Perfect for upcycling and textile recycling projects.",
    specifications: {
      Material: "100% Cotton Denim",
      Weight: "12-14 oz",
      Color: "Indigo blue",
      Contamination: "<1%",
      Processing: "Cut, sorted",
    },
    supplierInfo: {
      name: "Fashion Forward Ltd",
      established: "2010",
      certifications: ["OEKO-TEX", "ISO 9001"],
      rating: 4.7,
      totalReviews: 92,
    },
  },
  {
    id: 8,
    title: "Circuit Board Components",
    supplier: "TechRecycle Pro",
    location: "San Jose, CA",
    price: "₹2,500/ton",
    rating: 4.9,
    reviews: 67,
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    category: "electronics",
    quantity: "2 tons",
    minOrder: "50 kg",
    description:
      "Precious metal-rich electronic components from computer manufacturing. High value for metal recovery.",
    specifications: {
      Type: "Mixed PCBs",
      "Gold Content": "0.02%",
      "Silver Content": "0.1%",
      "Copper Content": "15%",
      Processing: "Depopulated",
    },
    supplierInfo: {
      name: "TechRecycle Pro",
      established: "2015",
      certifications: ["R2 Certified", "ISO 14001", "e-Stewards"],
      rating: 4.8,
      totalReviews: 145,
    },
  },
  {
    id: 9,
    title: "Wood Biomass Pellets",
    supplier: "Green Energy Solutions",
    location: "Portland, OR",
    price: "₹180/ton",
    rating: 4.6,
    reviews: 89,
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    category: "energy",
    quantity: "100 tons",
    minOrder: "5 tons",
    description:
      "Compressed wood pellets for energy production. Made from sawmill waste and wood processing byproducts.",
    specifications: {
      Material: "Mixed hardwood",
      Moisture: "<8%",
      "Ash Content": "<1%",
      Diameter: "6-8mm",
      "Calorific Value": "4,500 kcal/kg",
    },
    supplierInfo: {
      name: "Green Energy Solutions",
      established: "2018",
      certifications: ["FSC Certified", "ENplus A1"],
      rating: 4.5,
      totalReviews: 76,
    },
  },
  {
    id: 10,
    title: "Food Grade Cardboard",
    supplier: "PackagePro Inc",
    location: "Chicago, IL",
    price: "₹95/ton",
    rating: 4.4,
    reviews: 45,
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    category: "organic",
    quantity: "45 tons",
    minOrder: "1 ton",
    description: "Clean cardboard from food packaging operations. Suitable for recycling into new packaging materials.",
    specifications: {
      Type: "Corrugated cardboard",
      Grade: "Food grade",
      Contamination: "<0.5%",
      Moisture: "<12%",
      Processing: "Baled, sorted",
    },
    supplierInfo: {
      name: "PackagePro Inc",
      established: "2003",
      certifications: ["FDA Approved", "SQF Certified"],
      rating: 4.3,
      totalReviews: 58,
    },
  },
  {
    id: 11,
    title: "Rubber Tire Crumb",
    supplier: "TireRecycle Corp",
    location: "Dallas, TX",
    price: "₹320/ton",
    rating: 4.5,
    reviews: 38,
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    category: "organic",
    quantity: "60 tons",
    minOrder: "2 tons",
    description:
      "Recycled tire crumb from automotive tire processing. Perfect for playground surfaces and rubber products.",
    specifications: {
      Size: "1-4mm",
      "Steel Content": "<0.1%",
      "Textile Content": "<0.5%",
      Color: "Black",
      Processing: "Ambient ground",
    },
    supplierInfo: {
      name: "TireRecycle Corp",
      established: "2009",
      certifications: ["EPA Approved", "ISO 9001"],
      rating: 4.4,
      totalReviews: 71,
    },
  },
  {
    id: 12,
    title: "Glass Cullet - Mixed Colors",
    supplier: "GlassWorks Recycling",
    location: "Seattle, WA",
    price: "₹75/ton",
    rating: 4.2,
    reviews: 29,
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    category: "organic",
    quantity: "80 tons",
    minOrder: "3 tons",
    description: "Clean glass cullet from bottle manufacturing. Ready for remelting into new glass products.",
    specifications: {
      Type: "Soda-lime glass",
      Size: "5-50mm",
      Colors: "Mixed",
      Contamination: "<2%",
      Processing: "Crushed, cleaned",
    },
    supplierInfo: {
      name: "GlassWorks Recycling",
      established: "1998",
      certifications: ["ISO 9001", "GRI Certified"],
      rating: 4.1,
      totalReviews: 43,
    },
  },
]

export const categories = [
  { id: "all", name: "All Categories", count: products.length },
  { id: "metals", name: "Metals", count: products.filter((p) => p.category === "metals").length },
  { id: "chemicals", name: "Chemicals", count: products.filter((p) => p.category === "chemicals").length },
  { id: "textiles", name: "Textiles", count: products.filter((p) => p.category === "textiles").length },
  { id: "electronics", name: "Electronics", count: products.filter((p) => p.category === "electronics").length },
  { id: "energy", name: "Energy", count: products.filter((p) => p.category === "energy").length },
  { id: "organic", name: "Organic", count: products.filter((p) => p.category === "organic").length },
]
